---
- name: Create home-assistant directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ docker_base_dir }}/home-assistant"
    - "{{ docker_base_dir }}/home-assistant/config"

- block:
    - name: Create home-assistant docker compose file
      ansible.builtin.template:
        src: home-assistant/docker-compose.yml.j2
        dest: "{{ docker_base_dir }}/home-assistant/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: users
        mode: 0775
    - name: Create home-assistant systemd service file
      ansible.builtin.template:
        src: "docker-compose@.service.j2"
        dest: "/etc/systemd/system/docker-compose@home-assistant.service"
        mode: 0644
      vars:
        condition_path_is_mount_point: "/"
  notify: Restart home-assistant
