---
- name: Create bazarr directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ docker_base_dir }}/bazarr"
    - "{{ docker_base_dir }}/bazarr/config"

- block:
    - name: Create bazarr docker compose file
      ansible.builtin.template:
        src: bazarr/docker-compose.yml.j2
        dest: "{{ docker_base_dir }}/bazarr/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: users
        mode: 0775
    - name: Create bazarr systemd service file
      ansible.builtin.template:
        src: "docker-compose@.service.j2"
        dest: "/etc/systemd/system/docker-compose@bazarr.service"
        mode: 0644
      vars:
        condition_path_is_mount_point: "/"
  notify: Restart bazarr
