---
- name: Create jellyfin directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ docker_base_dir }}/jellyfin"
    - "{{ docker_base_dir }}/jellyfin/cache"
    - "{{ docker_base_dir }}/jellyfin/config"
    - "{{ docker_base_dir }}/jellyfin/logs"

- block:
    - name: Create jellyfin docker compose file
      ansible.builtin.template:
        src: jellyfin/docker-compose.yml.j2
        dest: "{{ docker_base_dir }}/jellyfin/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: users
        mode: 0775
    - name: Create jellyfin systemd service file
      ansible.builtin.template:
        src: "docker-compose@.service.j2"
        dest: "/etc/systemd/system/docker-compose@jellyfin.service"
        mode: 0644
      vars:
        condition_path_is_mount_point: "/"
  notify: Restart jellyfin