---
- name: Create prowlarr directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ docker_base_dir }}/prowlarr"
    - "{{ docker_base_dir }}/prowlarr/config"

- block:
    - name: Create prowlarr docker compose file
      ansible.builtin.template:
        src: prowlarr/docker-compose.yml.j2
        dest: "{{ docker_base_dir }}/prowlarr/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: users
        mode: 0775
    - name: Create prowlarr systemd service file
      ansible.builtin.template:
        src: "docker-compose@.service.j2"
        dest: "/etc/systemd/system/docker-compose@prowlarr.service"
        mode: 0644
      vars:
        condition_path_is_mount_point: "/"
  notify: Restart prowlarr
