---
- name: Create qbittorrent directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ docker_base_dir }}/qbittorrent"
    - "{{ docker_base_dir }}/qbittorrent/config"

- block:
    - name: Create qbittorrent docker compose file
      ansible.builtin.template:
        src: qbittorrent/docker-compose.yml.j2
        dest: "{{ docker_base_dir }}/qbittorrent/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: users
        mode: 0775
    - name: Create qbittorrent systemd service file
      ansible.builtin.template:
        src: "docker-compose@.service.j2"
        dest: "/etc/systemd/system/docker-compose@qbittorrent.service"
        mode: 0644
      vars:
        condition_path_is_mount_point: "/"
  notify: Restart qbittorrent
