---
- name: Create radarr directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ docker_base_dir }}/radarr"
    - "{{ docker_base_dir }}/radarr/config"

- block:
    - name: Create radarr docker compose file
      ansible.builtin.template:
        src: radarr/docker-compose.yml.j2
        dest: "{{ docker_base_dir }}/radarr/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: users
        mode: 0775
    - name: Create radarr systemd service file
      ansible.builtin.template:
        src: "docker-compose@.service.j2"
        dest: "/etc/systemd/system/docker-compose@radarr.service"
        mode: 0644
      vars:
        condition_path_is_mount_point: "/"
  notify: Restart radarr
