---
- name: Create sonarr directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ docker_base_dir }}/sonarr"
    - "{{ docker_base_dir }}/sonarr/config"

- block:
    - name: Create sonarr docker compose file
      ansible.builtin.template:
        src: sonarr/docker-compose.yml.j2
        dest: "{{ docker_base_dir }}/sonarr/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: users
        mode: 0775
    - name: Create sonarr systemd service file
      ansible.builtin.template:
        src: "docker-compose@.service.j2"
        dest: "/etc/systemd/system/docker-compose@sonarr.service"
        mode: 0644
      vars:
        condition_path_is_mount_point: "/"
  notify: Restart sonarr
